name: HawkScan
on:
  repository_dispatch:
    types: [integration-initial-test]
  workflow_dispatch:

jobs:
  hawkscan:
    name: HawkScan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create ${{ github.event.repository.name }} app directory
        run: mkdir -p common/build/integrationTests/hawkscan-action/apps/${{ github.event.repository.name }}
      - name: Navigate to ${{ github.event.repository.name }} app directory
        run: cd common/build/integrationTests/hawkscan-action/apps/${{ github.event.repository.name }}
      - name: Checkout vulny repo
        run: git clone https://github.com/${{ github.event.repository.full_name }}.git
      - name: Run ${{ github.event.repository.name }}
        run: docker compose up -d
      - name: Navigate to repo root directory
        run: cd /home/runner/work/${{ github.event.repository.full_name }}
      - name: Run HawkScan
        id: run-hawkscan
        uses: stackhawk/hawkscan-action@main
        with:
          apiKey: ${{ secrets.HAWK_API_KEY }}
          configurationFiles: ${{ github.event.client_payload.configFile }}
          sourceURL: ${{ github.event.client_payload.hawkscanSourceUrl }}
          version: ${{ github.event.client_payload.hawkscanVersion }}
          verbose: ${{ github.event.client_payload.verbose }}
        env:
          # APPLICATION_ID: ${{ github.event.client_payload.appId }}
          APP_ID: ${{ github.event.client_payload.appId }}
          NO_PROGRESS: true
          SARIF_ARTIFACT: true
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: stackhawk.sarif
          # Optional category for the results
          # Used to differentiate multiple results for one commit
          category: StackHawk
